# https://zh.wikipedia.org/wiki/YAML
# https://github.com/travis-ci/travis.rb#table-of-contents
# https://docs.travis-ci.com/
language: python
python: 
  - "3.8"

install:
  - pip install -r requirements.txt

script: 
  - python semanticscholar/tests/semanticscholar_tests.py

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJGY2MmJmZjI3LWJlMmYtNGEyZC1iODhlLTllYzhlZjZlODc2NQACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgtyZ3LhZai4tJ1CbOHLSGcctHIHBegdZJJFjcpIr2Ki4"
  on:
    tags: true
